services:
  postgres:
    image: postgres:16-alpine
    container_name: crypto_sentry_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crypto_sentry
      POSTGRES_USER: crypto_sentry
      POSTGRES_PASSWORD: crypto_sentry_password
    ports:
      - "5432:5432"
    volumes:
      - crypto_sentry_postgres_data:/var/lib/postgresql/data

volumes:
  crypto_sentry_postgres_data:

